#!/bin/bash

echo "Installing VS Code extensions..."

extensions=(
  "alefragnani.project-manager"
  "astro-build.astro-vscode"
  "bradlc.vscode-tailwindcss"
  "burkeholland.simple-react-snippets"
  "christian-kohler.path-intellisense"
  "codezombiech.gitignore"
  "DavidAnson.vscode-markdownlint"
  "dbaeumer.vscode-eslint"
  "donjayamanne.git-extension-pack"
  "donjayamanne.githistory"
  "dsznajder.es7-react-js-snippets"
  "eamodio.gitlens"
  "esbenp.prettier-vscode"
  "formulahendry.auto-rename-tag"
  "GitHub.copilot"
  "GitHub.copilot-chat"
  "github.vscode-github-actions"
  "golang.go"
  "hollowtree.vue-snippets"
  "jakob101.RelativePath"
  "jkjustjoshing.vscode-text-pastry"
  "kejun.devtoys"
  "mhutchie.git-graph"
  "mohsen1.prettify-json"
  "ms-azuretools.vscode-docker"
  "ms-python.isort"
  "ms-python.python"
  "ms-python.vscode-pylance"
  "ms-toolsai.jupyter"
  "ms-toolsai.jupyter-keymap"
  "ms-toolsai.jupyter-renderers"
  "ms-toolsai.vscode-jupyter-cell-tags"
  "ms-toolsai.vscode-jupyter-slideshow"
  "ms-vscode-remote.remote-containers"
  "ms-vscode-remote.remote-ssh"
  "ms-vscode-remote.remote-ssh-edit"
  "ms-vscode-remote.remote-wsl"
  "ms-vscode-remote.vscode-remote-extensionpack"
  "ms-vscode.cmake-tools"
  "ms-vscode.cpptools"
  "ms-vscode.cpptools-extension-pack"
  "ms-vscode.cpptools-themes"
  "ms-vscode.remote-explorer"
  "ms-vscode.remote-server"
  "oderwat.indent-rainbow"
  "PKief.material-icon-theme"
  "Postman.postman-for-vscode"
  "svelte.svelte-vscode"
  "toba.vsfire"
  "tomoki1207.pdf"
  "twxs.cmake"
  "usernamehw.errorlens"
  "vscodevim.vim"
  "Vue.volar"
  "Vue.vscode-typescript-vue-plugin"
  "wayou.vscode-todo-highlight"
  "wix.vscode-import-cost"
  "xabikos.ReactSnippets"
  "yoavbls.pretty-ts-errors"
  "ziyasal.vscode-open-in-github"
  "wmaurer.change-case"
  "austenc.tailwind-docs"
)

count=0

for extension in "${extensions[@]}"; do
  code --install-extension "$extension"
  count=$((count + 1))
done

echo "Done installing extensions."
echo "Installed $count extensions. Type 'code --list-extensions' to see them."
